IngredientNamesProductTag.delete_all
ProductTagAlias.delete_all
ProductTagGroup.delete_all
ProductTag.delete_all

group = ProductTagGroup.create(name: 'Condition')
  tag = group.product_tags.create(name: 'Frozen')
    tag.product_tag_aliases.create(alias: 'Frz')
  tag = group.product_tags.create(name: 'Fresh')
  tag = group.product_tags.create(name: 'Dried')
    tag.product_tag_aliases.create(alias: 'Dry')

group = ProductTagGroup.create(name: 'Cook')
  tag = group.product_tags.create(name: 'Grilled')
  tag = group.product_tags.create(name: 'Roasted')
  tag = group.product_tags.create(name: 'Cooked')
    tag.product_tag_aliases.create(alias: 'Ckd')
  tag = group.product_tags.create(name: 'Raw')

group = ProductTagGroup.create(name: 'Cut')
  tag = group.product_tags.create(name: 'Puree')
    tag.product_tag_aliases.create(alias: 'P')
  tag = group.product_tags.create(name: 'Sliced')
  tag = group.product_tags.create(name: 'Diced')
    tag.product_tag_aliases.create(alias: 'Dcd')
  tag = group.product_tags.create(name: 'Chopped')
  tag = group.product_tags.create(name: 'Chunks')
  tag = group.product_tags.create(name: 'Minced')
    tag.product_tag_aliases.create(alias: 'Mcd')
  tag = group.product_tags.create(name: 'Whole')
  tag = group.product_tags.create(name: 'Bone In')
    tag.product_tag_aliases.create(alias: 'B/I')
  tag = group.product_tags.create(name: 'Boneless')
    tag.product_tag_aliases.create(alias: 'Bnls')

group = ProductTagGroup.create(name: 'Dietary')
  tag = group.product_tags.create(name: 'Gluten Free')
    tag.product_tag_aliases.create(alias: 'G-F')
    tag.product_tag_aliases.create(alias: 'GF')
  tag = group.product_tags.create(name: 'Low Cholesterol')
    tag.product_tag_aliases.create(alias: 'Low Chol')
  tag = group.product_tags.create(name: 'Unsweetened')
    tag.product_tag_aliases.create(alias: 'Unsweet')
    tag.product_tag_aliases.create(alias: 'Unswt')
  tag = group.product_tags.create(name: 'Low Sodium')
    tag.product_tag_aliases.create(alias: 'LS')

group = ProductTagGroup.create(name: 'Misc')
  tag = group.product_tags.create(name: 'Concentrate')
    tag.product_tag_aliases.create(alias: 'Conc')
  tag = group.product_tags.create(name: 'Ready to Serve')
    tag.product_tag_aliases.create(alias: 'RtS')
  tag = group.product_tags.create(name: 'Canned')
    tag.product_tag_aliases.create(alias: 'Cnd')
  tag = group.product_tags.create(name: 'Base/Stock/Bouillon')
    tag.product_tag_aliases.create(alias: 'Base')
    tag.product_tag_aliases.create(alias: 'Stock')
    tag.product_tag_aliases.create(alias: 'Bouillon')

group = ProductTagGroup.create(name: 'Meat')
  tag = group.product_tags.create(name: 'Chicken')
    tag.product_tag_aliases.create(alias: 'Chk')
  tag = group.product_tags.create(name: 'Turkey')
  tag = group.product_tags.create(name: 'Beef')
  tag = group.product_tags.create(name: 'Pork')
  tag = group.product_tags.create(name: 'Lamb')
  tag = group.product_tags.create(name: 'Fish')
  tag = group.product_tags.create(name: 'Goat')
  tag = group.product_tags.create(name: 'Salmon')
  tag = group.product_tags.create(name: 'Tuna')