# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

NotationReplacement.create(to_replace: "1/2 ", replace_with: "0.5 ", execution_order: 10)
NotationReplacement.create(to_replace: "1/4 ", replace_with: "0.25 ", execution_order: 10)
NotationReplacement.create(to_replace: "x", replace_with: "-", execution_order: 10)
NotationReplacement.create(to_replace: "/", replace_with: "-", execution_order: 10)
NotationReplacement.create(to_replace: "-", replace_with: "|", execution_order: 999)

UnitAbbreviation.create(abbreviation: 'numbertencan', unit: '#10 can', execution_order: 102)
UnitAbbreviation.create(abbreviation: '#', unit: 'pound', execution_order: 102)
UnitAbbreviation.create(abbreviation: '#av', unit: 'pound', execution_order: 102)
UnitAbbreviation.create(abbreviation: '# av', unit: 'pound', execution_order: 102)
UnitAbbreviation.create(abbreviation: '#avg', unit: 'pound (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: '# avg', unit: 'pound (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'lbav', unit: 'pound (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'lb av', unit: 'pound (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'lbavg', unit: 'pound (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'lb avg', unit: 'pound (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'lb#', unit: 'pound', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'lbimport', unit: 'pound (import)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'lb import', unit: 'pound (import)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'kga', unit: 'kilogram (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'kgav', unit: 'kilogram (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'kg bag', unit: 'kilogram (bag)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'kgavg', unit: 'kilogram (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'kg av', unit: 'kilogram (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'kg up', unit: 'kilogram (minimum)', execution_order: 102)
UnitAbbreviation.create(abbreviation: '#up', unit: 'pound (minimum)', execution_order: 102)
UnitAbbreviation.create(abbreviation: '# up', unit: 'pound (minimum)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'pkg', unit: 'pack', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'rl', unit: 'roll', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'l', unit: 'liter', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'litre', unit: 'liter', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'liters', unit: 'liter', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'litres', unit: 'liter', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'lbs', unit: 'pound', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'sl', unit: 'slice', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'dzn', unit: 'dozen', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'z av', unit: 'ounce (average)', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'z avg', unit: 'ounce (average)', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'zav', unit: 'ounce (average)', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'zavg', unit: 'ounce (average)', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'oz av', unit: 'ounce (average)', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'ozav', unit: 'ounce (average)', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'ozavg', unit: 'ounce (average)', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'oz a', unit: 'ounce (average)', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'ltr', unit: 'liter', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'grm', unit: 'gram', execution_order: 104)
UnitAbbreviation.create(abbreviation: 'ga', unit: 'gallon', execution_order: 105)
UnitAbbreviation.create(abbreviation: 'gal', unit: 'gallon', execution_order: 105)
UnitAbbreviation.create(abbreviation: 'env', unit: 'env', execution_order: 106)
UnitAbbreviation.create(abbreviation: 'ft', unit: 'foot', execution_order: 107)
UnitAbbreviation.create(abbreviation: 'ml bottles', unit: 'milliliter', execution_order: 107)
UnitAbbreviation.create(abbreviation: 'ml bottle', unit: 'milliliter', execution_order: 107)
UnitAbbreviation.create(abbreviation: 'env', unit: 'enveloped bag', execution_order: 107)
UnitAbbreviation.create(abbreviation: 'ge', unit: 'gram (average)', execution_order: 108)
UnitAbbreviation.create(abbreviation: 'sh', unit: 'sheet', execution_order: 109)
UnitAbbreviation.create(abbreviation: 'sht', unit: 'sheet', execution_order: 110)
UnitAbbreviation.create(abbreviation: 'doz', unit: 'dozen', execution_order: 110)
UnitAbbreviation.create(abbreviation: 'dz', unit: 'dozen', execution_order: 110)
UnitAbbreviation.create(abbreviation: 'oz', unit: 'ounce', execution_order: 111)
UnitAbbreviation.create(abbreviation: 'gm', unit: 'gram', execution_order: 112)
UnitAbbreviation.create(abbreviation: 'gr', unit: 'gram', execution_order: 113)
UnitAbbreviation.create(abbreviation: 'qt', unit: 'quart', execution_order: 114)
UnitAbbreviation.create(abbreviation: 'kg', unit: 'kilogram', execution_order: 115)
UnitAbbreviation.create(abbreviation: 'lb', unit: 'pound', execution_order: 116)
UnitAbbreviation.create(abbreviation: 'ml', unit: 'milliliter', execution_order: 117)
UnitAbbreviation.create(abbreviation: '"', unit: 'inch', execution_order: 118)
UnitAbbreviation.create(abbreviation: 'in', unit: 'inch', execution_order: 119)
UnitAbbreviation.create(abbreviation: 'ct', unit: 'count', execution_order: 120)
UnitAbbreviation.create(abbreviation: 'roll ', unit: 'roll', execution_order: 121)
UnitAbbreviation.create(abbreviation: 'pk', unit: 'pack', execution_order: 122)
UnitAbbreviation.create(abbreviation: 'cs', unit: 'case', execution_order: 123)
UnitAbbreviation.create(abbreviation: 'case', unit: 'case', execution_order: 123)
UnitAbbreviation.create(abbreviation: 'set', unit: 'set', execution_order: 124)
UnitAbbreviation.create(abbreviation: 'pak', unit: 'pack', execution_order: 125)
UnitAbbreviation.create(abbreviation: 'pt', unit: 'pint', execution_order: 126)
UnitAbbreviation.create(abbreviation: 'pnt', unit: 'pint', execution_order: 127)
UnitAbbreviation.create(abbreviation: 'tab', unit: 'tablet', execution_order: 128)
UnitAbbreviation.create(abbreviation: 'pair', unit: 'pair', execution_order: 129)
UnitAbbreviation.create(abbreviation: 'crate', unit: 'crate', execution_order: 130)
UnitAbbreviation.create(abbreviation: 'bu', unit: 'bunch', execution_order: 131)
UnitAbbreviation.create(abbreviation: 'bn', unit: 'bunch', execution_order: 132)
UnitAbbreviation.create(abbreviation: 'kilo', unit: 'kilogram', execution_order: 133)
UnitAbbreviation.create(abbreviation: 'quart', unit: 'quart', execution_order: 134)
UnitAbbreviation.create(abbreviation: 'por', unit: 'portion', execution_order: 135)
UnitAbbreviation.create(abbreviation: 'box', unit: 'box', execution_order: 136)
UnitAbbreviation.create(abbreviation: 'cup', unit: 'cup', execution_order: 137)
UnitAbbreviation.create(abbreviation: '''s', unit: 'count', execution_order: 138)
UnitAbbreviation.create(abbreviation: 'each', unit: 'each', execution_order: 139)
UnitAbbreviation.create(abbreviation: 'tray', unit: 'tray', execution_order: 140)
UnitAbbreviation.create(abbreviation: 'trays', unit: 'tray', execution_order: 141)
UnitAbbreviation.create(abbreviation: 'ea', unit: 'each', execution_order: 142)
UnitAbbreviation.create(abbreviation: 'pc', unit: 'piece', execution_order: 143)
UnitAbbreviation.create(abbreviation: 'lt', unit: 'liter', execution_order: 144)
UnitAbbreviation.create(abbreviation: 'bx', unit: 'box', execution_order: 145)
UnitAbbreviation.create(abbreviation: 'yd', unit: 'yard', execution_order: 146)
UnitAbbreviation.create(abbreviation: 'z', unit: 'ounce', execution_order: 147)
UnitAbbreviation.create(abbreviation: 'g', unit: 'gram', execution_order: 148)
UnitAbbreviation.create(abbreviation: 'k', unit: 'kilogram', execution_order: 149)
UnitAbbreviation.create(abbreviation: 'l', unit: 'liter', execution_order: 150)
UnitAbbreviation.create(abbreviation: 'm', unit: 'meter', execution_order: 151)
UnitAbbreviation.create(abbreviation: 'q', unit: 'quart', execution_order: 152)
UnitAbbreviation.create(abbreviation: 'c', unit: 'count', execution_order: 153)
UnitAbbreviation.create(abbreviation: 'e', unit: 'each', execution_order: 154)


PackSize.create(description: 'DONUT CAKE MINI .5OZ VARTY PCK', pack_size: '4-50 CT')
PackSize.create(description: 'BAG GARBAGE REG CLR 42X48 CDN', pack_size: '125-1 EACH')
PackSize.create(description: 'GLOVE RUBBER YEL SM', pack_size: '10-12 CT')
PackSize.create(description: 'ICE FRUIT CAFFE LATTE', pack_size: '1-11LT')
PackSize.create(description: 'KETCHUP BTLD TOMATO FRENCH S', pack_size: '12-500 ML')
PackSize.create(description: 'SAUCE SWEET   SOUR DIPPING IND', pack_size: '100-28 ML')
PackSize.create(description: 'SYRUP IRISH CRM', pack_size: '2-750ML')
PackSize.create(description: 'DOUGH SCONE BLUBRY', pack_size: '40-10 OZ')
PackSize.create(description: 'SHELF WIRE CHROME PLATED 24X36', pack_size: '4-EACH')
PackSize.create(description: 'BOE BIFT MINUTE DELIC AA 4OZ SG', pack_size: '40-4 OZ')
PackSize.create(description: 'PLUME RAYEE S/GLUTEN', pack_size: '1-10 LB')
PackSize.create(description: 'TORTILLA CORN YEL 6 IN 6 OZ', pack_size: '12-5 DZ')
PackSize.create(description: 'CARROT JMBO ASIAN', pack_size: '1-10 KG')
PackSize.create(description: 'DRINK TROPICAL CONC', pack_size: '2-4 LT')
PackSize.create(description: 'GYRO BEEF   LAMB CKD SLCD RTS', pack_size: '4-6 LB')
PackSize.create(description: 'PEPPERONI PIZZA SLC SMKD 75MM', pack_size: '12-500 GR')
PackSize.create(description: 'BAG GARBAGE PLSTC CLR 42X48', pack_size: '1-200CT')
PackSize.create(description: 'PLATTER RECT SLATE', pack_size: '6-14X11')
PackSize.create(description: 'BREAD WHL WHEAT 100% TEXAS TST', pack_size: '10-675 GR')
PackSize.create(description: 'LID PLAS 32TJ/12B/85J/16MJ32', pack_size: '5/100CT')
PackSize.create(description: 'BAG FOR HCKRY WOOD CHIP', pack_size: '1-1EACH')
PackSize.create(description: 'DESSERT BAR BRULEE RASP WHT CH', pack_size: '4/3 LBS')
PackSize.create(description: 'BROC TIGE IQF', pack_size: '12-1 KG')
PackSize.create(description: 'BAG SANDWICH GREASE RESIST WHT', pack_size: '1-1000CT')
PackSize.create(description: 'GLASS COLLINS ESQUIRE', pack_size: '36-12 OZ')
PackSize.create(description: 'RICE LONG GRAIN 4% BRKN', pack_size: '1/25 LB')
PackSize.create(description: 'JUICE ORANGE PORTION', pack_size: '48-3 OZ')
PackSize.create(description: 'GARLIC WHL BULB FRESH', pack_size: '1-30 LB')
PackSize.create(description: 'TILAPIA WHL GUTTED SCALED', pack_size: '1-18 LB')
PackSize.create(description: 'LID FOIL F/ RECT CONT KENT', pack_size: '500-5X8')
PackSize.create(description: 'MUFFIN BATTER BLUBRY PASSN', pack_size: '1-9LB')
PackSize.create(description: 'PAN STM TBL 4 DEEP 607004', pack_size: '6-FULL')
PackSize.create(description: 'POTATO FRY 3/8in CC', pack_size: '6-4.5 LB')
PackSize.create(description: 'FUEL LAMP LIQUID WAX', pack_size: '4-1 GAL')
PackSize.create(description: 'CONTAINER PLAS HNG 6X3 B/C HEX', pack_size: '2/60 CT')
PackSize.create(description: 'SAUCE CURRY KORMA', pack_size: '2-2.2KG')
PackSize.create(description: 'TUNA ALBACORE SOLID WHT', pack_size: '6-1.88KG')
PackSize.create(description: 'PLATE PAPER WHT RC 10.5in', pack_size: '4-125 CT')
PackSize.create(description: 'TRAY CAFE PLAS BURG', pack_size: '24-EACH')
PackSize.create(description: 'TORTE BIENENSTICH VAN.W PRALN', pack_size: '2-6.6 LB')
PackSize.create(description: 'POTATO SWEET FRESH', pack_size: '1-40 LB')
PackSize.create(description: 'STRAW PLAS CKTL UNWRP RED 7.75', pack_size: '12/500CT')
PackSize.create(description: 'TOM ROSE 6X6 FR', pack_size: '1-25 LB')
PackSize.create(description: 'PUREE MEAT VARIETY PK', pack_size: '48-90 GM')
PackSize.create(description: 'RAVIOLI MUSHROOM PORTABLO DIMD', pack_size: '2-5LB')
PackSize.create(description: 'STEAK RIB AAA 14 OZ OCF', pack_size: '12-397 GM')
PackSize.create(description: 'BOX BUS BLK 7 IN DP', pack_size: '1-20X15')
PackSize.create(description: 'STORE  N POUR BACKUP CNTR', pack_size: '12-EACH')
PackSize.create(description: 'PLATE FOAM UL WHT 7in', pack_size: '8-125 CT')
PackSize.create(description: 'CHICKEN BRST FIL CRUNCHY RUF', pack_size: '2-2 KG')
PackSize.create(description: 'PORK BACK BNLS S/C 1/4in', pack_size: '6-4.17AV')
PackSize.create(description: 'PIE PEACH UNBKD 8 IN', pack_size: '6-680 GM')
PackSize.create(description: 'CHICKEN BRST BLS SKLS FRZN', pack_size: '1-5 KG')
PackSize.create(description: 'LID DOME FITS P9110Z', pack_size: '1-195CT')
PackSize.create(description: 'VEG BLEND TURNIP&CARROT MASHED', pack_size: '3-2 KG')
PackSize.create(description: 'YOGURT VANILLA GREEK 2% IOGO', pack_size: '6-750 GR')
PackSize.create(description: 'TORTE CHOCOLATE BLK FOREST 10', pack_size: '2-3 LB')
PackSize.create(description: 'SUPPLEMENT SHAKE CHOCOLATE NO', pack_size: '50-4 OZ')
PackSize.create(description: 'TOPPING WHIPPED N/DAIRY', pack_size: '12-500GR')
PackSize.create(description: 'YOG SOURCE ASSORT', pack_size: '48-100 GM')
PackSize.create(description: 'PORK RIB BCK 26 DOWN', pack_size: '1-8.5KG')
PackSize.create(description: 'SAUSAGE LAMB MERQUEZ', pack_size: '6-454GR')
PackSize.create(description: 'CAKE POUND ASST 30 SLICES', pack_size: '6-2.3 LB')
PackSize.create(description: 'BAG PAPER BRN 25LB SHORTY', pack_size: '1/500 CT')
PackSize.create(description: 'DESSERT BAR ASST #1 8 OZ', pack_size: '4-3 LB')
PackSize.create(description: 'POTATO RED #1 FRESH', pack_size: '1-20#')
PackSize.create(description: 'BAG PLAS DAY SUNDAY BLK', pack_size: '1-2000CT')
PackSize.create(description: 'CARROT SHRD', pack_size: '4-5 LB')
PackSize.create(description: 'SYRUP CHOCOLATE FLAVOURED', pack_size: '2-750ML')
PackSize.create(description: 'STEAK TOP SIRLOIN AAARACC3/4', pack_size: '20-284 GM')
PackSize.create(description: 'ARUGULA FRESH HYDROPONIC', pack_size: '1-12 CT')
PackSize.create(description: 'COOKIE GINGER SNAPS', pack_size: '16-340 GR')
PackSize.create(description: 'POTATO MASHED INSTANT W/VIT C', pack_size: '6-5.31LB')
PackSize.create(description: 'SAUCE MIX ALFREDO', pack_size: '8/16 OZ')
PackSize.create(description: 'STIRRER PLAS BRN FLAT 4.5', pack_size: '10-1000PC')
PackSize.create(description: 'CHEESE CHEDDAR SLCD MILD', pack_size: '1-6KG')
PackSize.create(description: 'COFFEE GOURM K-CUP HZLNT', pack_size: '1-50 CT')
PackSize.create(description: 'COVER PAN SS 10.25IN', pack_size: '1-10.25in')
PackSize.create(description: 'CONTAINER PLAS HNG BLK/CLR HEX', pack_size: '1-100 CT')
PackSize.create(description: 'SAUCE SESAME', pack_size: '2-4LT')
PackSize.create(description: 'PORK TENDERLOIN COV FRZN', pack_size: '3-4.5 KG')
PackSize.create(description: 'SPICE WASABI PWDR', pack_size: '10-1 KG')
PackSize.create(description: 'ROSBIF PUREE SG', pack_size: '3-1.7KG')
PackSize.create(description: 'CHAMP SHITAKE FR', pack_size: '1-5 LB')
PackSize.create(description: 'DRINK SPARKLER CHINOTTO', pack_size: '24-355 ML')
PackSize.create(description: 'CHICKEN WING BBQ FULY CKD', pack_size: '1-4 KG')
PackSize.create(description: 'PEA GREEN ASST', pack_size: '6-2 KG')
PackSize.create(description: 'CONTAINER FOAM FISH BOX W/LID', pack_size: '1-EA')
PackSize.create(description: 'MUSCADE MOULUE BP', pack_size: '12-540 GR')
PackSize.create(description: 'SUPPLEMENT ENSURE PLUS CHOC', pack_size: '24/8 OZ')
PackSize.create(description: 'MELON WATERMELON SDLS FRSH', pack_size: '1/4-5 CT')
PackSize.create(description: 'NET PLANCHER S/RINC(WASH N WALK)', pack_size: '1-9.46LT')
PackSize.create(description: 'DETERGENT MACH SOLID POWER', pack_size: '6-9 LB')
PackSize.create(description: 'SPOON COFFEE ESPRSO THOR SM', pack_size: '24-EA')
PackSize.create(description: 'POT STOCK ALUM 8 GAUGE', pack_size: '1-16 QT')
PackSize.create(description: 'SUPPLEMENT ENSURE PLUS STRWBRY', pack_size: '24-235ML')
PackSize.create(description: 'SUCRE BLC GRANULE SAC', pack_size: '1-20 KG')
PackSize.create(description: 'BREAD WHITE CLUBHOUSE 3/4in', pack_size: '1-8 EA')
PackSize.create(description: 'PASTA FETTUCCELLE #6 68001', pack_size: '20-500 GM')
PackSize.create(description: 'ICE CREAM CONE CANADN', pack_size: '36-120 ML')
PackSize.create(description: 'DANOISE CHOC AVALANCHE 4.1OZ PAC SG KAS', pack_size: '60-115GR')
PackSize.create(description: 'SHOOT CORN inORGANICin', pack_size: '1-8 LB')
PackSize.create(description: 'Dart Hot/Cold Cup Lid 8ozPlas WhtFltVntd', pack_size: '1000/cs')
PackSize.create(description: 'SCALLOP SEA DRY 10/20 CT CDN', pack_size: '1-8 LB')
PackSize.create(description: 'STEAK PORTERHOUSE AAA 24OZ FZN', pack_size: '9-680 GM')
PackSize.create(description: 'BOIS SOYA VANIL BIO TETRA', pack_size: '12-946 ML')
PackSize.create(description: 'SAUCE SOY (PLASTIC JUG)', pack_size: '4-3.78LT')
PackSize.create(description: 'MILK HOMO JUG', pack_size: '9-2 LT')
PackSize.create(description: 'BREAKFAST BAR TRIX', pack_size: '96/1.42OZ')
PackSize.create(description: 'SALSA FRESH HOT', pack_size: '1-8 LB')
PackSize.create(description: 'SALT SEASONED NO MSG', pack_size: '1-2KG')
PackSize.create(description: 'Lemons Sunkist 165/cs (116060)', pack_size: '165ct')
PackSize.create(description: 'BRUSH POT SCRUB BLUE', pack_size: '1/8 IN')
PackSize.create(description: 'CONTAINER TRASH WALL HUGR GREY', pack_size: '2-1.00EA')
PackSize.create(description: 'STEAK SIRLOIN CC FLAT GT 6OZ', pack_size: '24-170 GM')
PackSize.create(description: 'LETTUCE BABY ORGANIC CLAMSHELL', pack_size: '8-5 OZ')
PackSize.create(description: 'ONION RED RING 1/4 NO CNTR', pack_size: '1-5 LB')
PackSize.create(description: 'CHEESE CREAM GARDEN VEGETABLE', pack_size: '100/1 OZ')
PackSize.create(description: 'BISC AVOINE RAISIN VRAC', pack_size: '1-10 LB')
PackSize.create(description: 'BEEF STRIPLOIN STEAK AAA', pack_size: '16-9 OZ')
PackSize.create(description: 'AVOCADO FRESH   READY TO USE', pack_size: '1-36-48C')
PackSize.create(description: 'CAKE TIRAMISU VEGAN 10', pack_size: '1-1CT')
PackSize.create(description: 'SODA ORANGE CRM DARE DEVIL', pack_size: '24-355ML')
PackSize.create(description: 'KIWI FRUIT BULK', pack_size: '1-23 LB')
PackSize.create(description: 'SOUP BORSCHT RUSSIAN FRZ', pack_size: '8-64 OZ')
PackSize.create(description: 'EGG LIQUID WHL ULTRA', pack_size: '12-1 KG')
PackSize.create(description: 'CABBAGE GREEN SHRED SLAW 1/4', pack_size: '4-5 LB')
PackSize.create(description: 'BEAN GREEN STRAINED BABY FOOD', pack_size: '12-128 ML')
PackSize.create(description: 'SAUCE TERIYAKI SODIUM RDUC', pack_size: '12-350 ML')
PackSize.create(description: 'TEA PPRMNT FOIL ENV', pack_size: '6-25 CT')
PackSize.create(description: 'GELATIN ORANGE', pack_size: '24-3OZ.')
PackSize.create(description: 'TRUFFLE BLK WHL PLD', pack_size: '1-100 GR')
PackSize.create(description: 'FLOOR FINISH OASIS PRO NO-GLAR', pack_size: '1-5 GAL')
PackSize.create(description: 'APTZR PEROGY POTATO & CHDR', pack_size: '4-1KG')
PackSize.create(description: 'KIT CUTLERY LUNCH/SUPPER', pack_size: '1-250 CT')
PackSize.create(description: 'CABBAGE SHRED 1/8  RC CAR', pack_size: '4-5 LB')
PackSize.create(description: 'SAUSAGE PORK & BEEF', pack_size: '1-5 KG')
PackSize.create(description: 'FROM CHED JNE DOUX 0.7OZ', pack_size: '100-21 GM')
PackSize.create(description: 'Banana (Green)', pack_size: 'Cs/18Kg')
PackSize.create(description: 'BOL SALADE PLST PERLE TRANSP 6', pack_size: '12-EA')
PackSize.create(description: 'CRANBERRY DRIED CANADA', pack_size: '1-5 LB')
PackSize.create(description: 'CEREAL SPECIAL K', pack_size: '12-435 GR')
PackSize.create(description: 'MILK CHOCOLATE 1% ESL CANADA', pack_size: '24-250 ML')
PackSize.create(description: 'TARTE CREME BANA SG', pack_size: '6-25 OZ')
PackSize.create(description: 'STEAK STRIPLOIN AAA BSO 6 OZ', pack_size: '32-6 OZ')
PackSize.create(description: 'PLATE BIODEG WHEAT ENVIRO 9', pack_size: '4-125 CT')
PackSize.create(description: 'BEEF BACK RIB AA CARGILL', pack_size: '1-30 KG*')
PackSize.create(description: 'COFFEE GRND REG ORGANIC 12OZ', pack_size: '6-12OZ')
PackSize.create(description: 'FISH FILET ARTIC CHAR S/ON PBO', pack_size: '1-10#')
PackSize.create(description: 'BUN SESAME BLK   WHT', pack_size: '48-70 GR')
PackSize.create(description: 'PAIN MOELLEUX BLC 3.2OZ CUI SG', pack_size: '72-90 GR')
PackSize.create(description: 'COFFEE CAPPUC REG FRNCH VANILA', pack_size: '6-2LB')
PackSize.create(description: 'PASTA SPAGHETTI', pack_size: '20-500 GM')
PackSize.create(description: 'HADDOCK FIL BEER BATR 2-4 OZ', pack_size: '1-10 LB')
PackSize.create(description: 'SHELF WIRE EXPOXY COATED GREEN', pack_size: '1-18X48')
PackSize.create(description: 'ICE CREAM SORBET BLOOD ORG', pack_size: '1-4.25LT')
PackSize.create(description: 'SUGAR SUB PACKET YELLOW-46007', pack_size: '2000/1 GM')
PackSize.create(description: 'SALAD BEAN FIVE SUPER CHARGE', pack_size: '12-115 GR')
PackSize.create(description: 'Lobster Salad', pack_size: '12lbs')
PackSize.create(description: 'COFFEE BEAN FILTRO MED', pack_size: '6-1KG')
PackSize.create(description: 'Sauce Green Curry 3/4kg (GMC) (10077)', pack_size: '3/4kg')
PackSize.create(description: 'EGGROLL VEGETABLE AKA', pack_size: '72-3 OZ')
PackSize.create(description: 'STRAINER FINE RND 6  DIAM CDN', pack_size: '12-EACH')
PackSize.create(description: 'PORK BACK RIB PRTNS FULLY CKD', pack_size: '24-8 OZ')
PackSize.create(description: 'VEGETARIAN MEAT MEATBALLS', pack_size: '12-383 GM')
PackSize.create(description: 'ROLL PRETZEL BAVARIAN GRMT 4OZ', pack_size: '80/4 OZ')
PackSize.create(description: 'MELON CANTALOUPE FCY FRSH AKA', pack_size: '1-9 CT')
PackSize.create(description: 'POPCORN MCRO  SMART POP  BOWL', pack_size: '36-70 GR')
PackSize.create(description: 'COOKIE OATMEAL BLUBRY   CHOC', pack_size: '24-85 GR')
PackSize.create(description: 'CHICKEN WING HOT & SPCY', pack_size: '1-4 KG')
PackSize.create(description: 'PAN FOOD 1/2 SZ 6  DP CLR', pack_size: '6-EACH')
PackSize.create(description: 'RAZOR BIC INDIVIDUALLY WRPD', pack_size: '500-CS')
PackSize.create(description: 'GARLIC CLOVE BULK FRESH LARGE', pack_size: '1-5 LB')
PackSize.create(description: 'CARROT MATCHSTICK 1/8  FRSH', pack_size: '1-5 LB')
PackSize.create(description: 'GLASS BEVERAGE GBRLTR DURTF', pack_size: '36-14OZ')
PackSize.create(description: 'LID FOIL BOARD LAM 9  RND HVY', pack_size: '1-500')
PackSize.create(description: 'COFFEE COL FLTR DECAF IN ROOM', pack_size: '100-20GM')
PackSize.create(description: 'DRINK BLACKBERRY SPRKLG', pack_size: '24/8.4 OZ')
PackSize.create(description: 'BRUSH CLEANING 24in WHT HNDL', pack_size: '12-EACH')
PackSize.create(description: 'NAPKIN DINNER NULINEN NAT BRGO', pack_size: '15-100 EA')
PackSize.create(description: 'CONTAINER PLAS RECT LRG 2C BLK', pack_size: '2-75 CT')
PackSize.create(description: 'COFFEE BEAN DARK ROAST DRIP', pack_size: '30-64 GR')
PackSize.create(description: 'ENTREE PORK PUREE', pack_size: '10-1 KG')
PackSize.create(description: 'FLOWER EDIBLE ORCHID', pack_size: '1-50CT')
PackSize.create(description: 'BEAN BAKED IN TOMATO SAUC', pack_size: '6-100 OZ')
PackSize.create(description: 'CUP PLAS KIDS COMBO JUNGLE', pack_size: '250-12 OZ')
PackSize.create(description: 'BEEF BURGER SIRLOIN 7OZ', pack_size: '24-7OZ')
PackSize.create(description: 'ZUCCHINI SLI QUARTERS', pack_size: '6-2 KG')
PackSize.create(description: 'CELERI RAVE FR', pack_size: '1-20 LB')
PackSize.create(description: 'PATE MUFFIN CITRON PAVOT SG CH', pack_size: '1-3.62KG')
PackSize.create(description: 'OLIVE KALAMATA COLSSL', pack_size: '1-12 KG')
PackSize.create(description: 'CABBAGE NAPA WGA FRSH', pack_size: '1-65 LB')
PackSize.create(description: 'SALAD FRUIT AL FRESCO NO PRESV', pack_size: '1-8 LB')
PackSize.create(description: 'CONT DELI PLST TRANSP COMBO 8OZ', pack_size: '240-8OZ')
PackSize.create(description: 'CER CHEERIOS BTE JNE', pack_size: '10-570 GR')
PackSize.create(description: 'CHICKEN BRST 6OZ SUPR TR MAR', pack_size: '1-4 KG')
PackSize.create(description: 'VEGETABLE MIX MOUNTAIN', pack_size: '4-5LB')
PackSize.create(description: 'MEAT GYRO CONE HALAL MED', pack_size: '2-20 LB')
PackSize.create(description: 'BOWL PLAS BLK SQUARE 64OZ', pack_size: '1-150CT')
PackSize.create(description: 'MEATBALL PRECOOKED .5 OZ', pack_size: '1-10 LB')
PackSize.create(description: 'TOMATO FRESH ORGANIC 2LYR', pack_size: '1-22#')
PackSize.create(description: 'TART RAISIN IND WRPD CDN', pack_size: '48-78G')
PackSize.create(description: 'PEPPERONI PORK  BEEF DRY CURED', pack_size: '2-3.4 KG')
PackSize.create(description: 'mushroom', pack_size: '5#')
PackSize.create(description: 'LID PLAS DOME F/ 8OZ HOT CUP', pack_size: '10/100 CT')
PackSize.create(description: 'LID PLAS 8 OZ', pack_size: '1000-EACH')
PackSize.create(description: 'SPICE PEPPER BLK CRACKED', pack_size: '1/1 LB')
PackSize.create(description: 'TURKEY WHL GFT BOX 5-7KG', pack_size: '1-7 KG')
PackSize.create(description: 'BREAD WHEATBERRY DELI11/16inSLI', pack_size: '6/32 OZ')
PackSize.create(description: 'LIME FRESH', pack_size: '1-175 CT')
PackSize.create(description: 'ENTREE BEAN GARBANZO & VEG', pack_size: '6-1.3 KG')
PackSize.create(description: 'WAFFLE BELGIAN RND BKD 7  INDW', pack_size: '36-5 OZ')
PackSize.create(description: 'FILLING PIE CHERRY HVY FRT MED', pack_size: '1-14.5KG')
PackSize.create(description: 'PUDDING MIX CHOC INS SUGR FREE', pack_size: '12/3.5 OZ')
PackSize.create(description: 'TURKEY BRST SPLIT SEMI-BNLS', pack_size: '4-4KG')
PackSize.create(description: 'BERRY MIXED IQF', pack_size: '1-11 LB')
PackSize.create(description: 'MUSTARD BROWN SPCY BOTTLES', pack_size: '12/12 OZ')
PackSize.create(description: 'Homo milk', pack_size: '1L')
PackSize.create(description: 'BASKET CULINARY FINE', pack_size: '36-EACH')
PackSize.create(description: 'KIT CUTLERY K/F/S/NP/S&P WHT', pack_size: '250/EA')
PackSize.create(description: 'CREAM CREME FRAICHE', pack_size: '6-475 GR')
PackSize.create(description: 'LID PAN FOOD HALF SZ BLU CDN', pack_size: '6-EACH')
PackSize.create(description: 'QUICHE SPINACH /GOAT CH/REDPEP', pack_size: '12-4.25in')
PackSize.create(description: 'CLEANER DEGRSR HD KITN CAN', pack_size: '2-4 LTR')
PackSize.create(description: 'TORTILLA WRAP TOMATO BASIL 12in', pack_size: '6-10CT')
PackSize.create(description: 'BACON CANADIAN PEAMEAL DELI TW', pack_size: '2-4 KG')
PackSize.create(description: 'ENTREE TURKEY DINNER SPCL DIET', pack_size: '12-270 GM')
PackSize.create(description: 'ICE DAIRY PISTACCHIO', pack_size: '1-4 LT')
PackSize.create(description: 'CABBAGE NAPA BLND RAD/ JLN CAR', pack_size: '4-2LB')
PackSize.create(description: 'SAUCE HOT BEAN', pack_size: '24-250 ML')
PackSize.create(description: 'SOAP HAND ANTIBACTERIAL FOAM', pack_size: '12-800 ML')
PackSize.create(description: '#Hoffmaster Doily 10in Lace Cambridge', pack_size: '1000/cs')
PackSize.create(description: 'LID PLAS VENT 8/12SJ/5/8/10B20-20JL', pack_size: '10/100CT')
PackSize.create(description: 'LINER ROLL 33X40 16 MC NAT', pack_size: '250/33 GAL')
PackSize.create(description: 'SALSA CHUNKY MILD', pack_size: '2-3.8 LT')
PackSize.create(description: 'ENTREE BEEF POT ROAST MEAL', pack_size: '12-330 GM')
PackSize.create(description: 'BEAN YEL WAX FRESH', pack_size: '1-10 LB')
PackSize.create(description: 'STEAK TOP SIRL AAA CC BB LP 4Z', pack_size: '40-113 GM')
PackSize.create(description: 'CELERY FRESH', pack_size: '1-6 CT')
PackSize.create(description: 'QUINCE FRESH', pack_size: '1-28#')
PackSize.create(description: 'SOUP CHICKEN VEG IND PRTN', pack_size: '24-200 GM')
PackSize.create(description: 'BASE SCE ROSBIF', pack_size: '1-4.5 KG')
PackSize.create(description: 'HAM CAPICOLA BUTT HOT', pack_size: '1/5-6#AV')
PackSize.create(description: 'CROISSANT PLAIN UNBAKED', pack_size: '180-49 GR')
PackSize.create(description: 'CAKE LOAF VAR PK G/L/S FREE', pack_size: '24-454 GR')
PackSize.create(description: 'LAMB RACK FRNCHD CAP OFF AUST', pack_size: '14-20-24Z')
PackSize.create(description: 'BAGEL MULTI GRAIN', pack_size: '36-4 OZ')
PackSize.create(description: 'STEAK STRIP MANHTN AAA FZ', pack_size: '24-227GM')
PackSize.create(description: 'NAPKIN WHITE 2 COLR SERVRITE', pack_size: '20-300 CT')
PackSize.create(description: 'CREME GLA CHOC S/NOIX S/GLUT', pack_size: '2-4 LTR')
PackSize.create(description: 'HERB FRESH LMNADE KIT', pack_size: '1-2 LBS')
PackSize.create(description: 'PASTA FETTUCCINE NEST #233', pack_size: '8-500 GR')
PackSize.create(description: 'Certo Teaspoon PP Wht MediumWeight Wrppd', pack_size: '1000/cs')
PackSize.create(description: 'SAUCE BUFFALO', pack_size: '2-3.8 LT')
PackSize.create(description: 'DRESSING MAYO MIRACLE WHIP', pack_size: '2-3.78LT')
PackSize.create(description: 'ICE CREAM BTRSCH RIPPLE', pack_size: '1-11.4LT')
PackSize.create(description: 'BAMBOO SHOOT MENMA SEASND 2.2#', pack_size: '10-1KG')
PackSize.create(description: 'SPATULA BAKER SS BLADE PLS HND', pack_size: '1-10in')
PackSize.create(description: 'CHEESE MONTEREY JACK GRLC CHIV', pack_size: '2-2.5KG')
PackSize.create(description: 'DRINK GINGER ALE POMEGRANATE', pack_size: '24-355 ML')
PackSize.create(description: 'JUICE GRAPE APPLE PLAS', pack_size: '24-300 ML')
PackSize.create(description: 'BREAD WHITE SOFT GLUTEN FREE', pack_size: '6-680GR')
PackSize.create(description: 'DETERGENT POT & PAN SUNLIGHT', pack_size: '2-6 LT')
PackSize.create(description: 'JACKET CHEF BLK SHORT SLEEVE', pack_size: '1-SMALL')
PackSize.create(description: 'SPRINKLE CHOCOLATE FLAVOURED', pack_size: '1-3 KG')
PackSize.create(description: 'VEGETABLE MIX NACHO', pack_size: '2-2.5 LB')
PackSize.create(description: 'CHEESE CHEDDAR SLICING', pack_size: '1-4.75KG')
PackSize.create(description: 'LETTUCE ROMAINE GOURM SNGLS', pack_size: '2-5 LB')
PackSize.create(description: 'MOLASSES BLACKSTRAP CROSBY', pack_size: '2-5KG')
PackSize.create(description: 'SCE VIANDE ROMAINE SG', pack_size: '4-2 KG')
PackSize.create(description: 'TOAST PLAIN MELBA', pack_size: '12-400 GR')
PackSize.create(description: 'RASPBERRY WHL WHT CHOC DIP 150', pack_size: '5-1 KG')
PackSize.create(description: 'TOWEL PAPER MULTIFOLD 1PLY WHT', pack_size: '16-250 CT')
PackSize.create(description: 'RICE WILD COOKED TINS', pack_size: '12-15 OZ')
PackSize.create(description: 'APPLES, GOLDEN DELICIOUS WAXF 88 4696', pack_size: '88 CT')
PackSize.create(description: 'WATER SPRING DEP', pack_size: '48/8 OZ')
PackSize.create(description: 'CAKE SHEET RASP CRM', pack_size: '2-2.4 KG')
PackSize.create(description: 'STEAK RIBEYE 10OZ AAA CDN FRZN', pack_size: '20-10Z AV')
PackSize.create(description: 'CHICKEN THIGH BNLS SKON FRF', pack_size: '1-4.54KG')
PackSize.create(description: 'PAPAYA, 9/10 CT PAP01', pack_size: '10 CT')
PackSize.create(description: 'CRAWFISH WHL CKD 15/18 IQF', pack_size: '2-5LB')
PackSize.create(description: 'CHICKEN BREAST SUPREME 5-6 OZ', pack_size: '1-5 KG')
PackSize.create(description: 'MIX BISCUIT SCONE', pack_size: '6-2 KG')
PackSize.create(description: 'Leek Bunch', pack_size: '12 bunch - each')
PackSize.create(description: 'WIENER ALL-MEAT PORK BBQ', pack_size: '10-1KG')
PackSize.create(description: 'BOTTLE SQUEEZE REPL LID', pack_size: '1-20 EA')
PackSize.create(description: 'FORK DINNER EURPN MODENA', pack_size: '12-EACH')
PackSize.create(description: 'SOUP BEAN MEDLEY HARTLND', pack_size: '3-4 LB')
PackSize.create(description: 'CONTAINER PAPER W/LID 32 OZ', pack_size: '10-25 CT')
PackSize.create(description: 'CARROT FRESH ORGANIC RNBW JCE', pack_size: '1-25 LB')
PackSize.create(description: 'ROLL CINNAMON BRIOCHE 0% T/FAT', pack_size: '60-100 GR')
PackSize.create(description: 'MANGO FRUIT FRSH TOMMY ATKINS', pack_size: '1-9 CT')
PackSize.create(description: 'CHEESE MOZZARELLA SLCE FRZN', pack_size: '12-500 GR')
PackSize.create(description: 'HAIRNET NYLON INVISIBLE BRN', pack_size: '10-144CT')
PackSize.create(description: 'BOX FOOD PERF 18X26X5', pack_size: '1-EA')
PackSize.create(description: 'MUSHROOM FRESH LARGE', pack_size: '1-10LB')
PackSize.create(description: 'BEET SLICED', pack_size: '6-2.84LT')
PackSize.create(description: 'SAUCE GARLIC WHT', pack_size: '2-3.8LT')
PackSize.create(description: 'SAUCE SOY TIN', pack_size: '4-3.78LT')
PackSize.create(description: 'CAKE LEMON MEYER LAVA', pack_size: '32-4OZ')