# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#


#require File.expand_path(File.dirname(__FILE__))+"/seeds/seed_ingredient_names.rb"
#require File.expand_path(File.dirname(__FILE__))+"/seeds/seed_nutritional_source_names.rb"
#require File.expand_path(File.dirname(__FILE__))+"/seeds/seed_product_names.rb"
#require File.expand_path(File.dirname(__FILE__))+"/seeds/seed_product_tags.rb"
require File.expand_path(File.dirname(__FILE__))+"/seeds/seed_product_pack_sizes.rb"


NotationReplacement.delete_all
UnitAbbreviation.delete_all
IngredientTypeAbbreviation.delete_all

NotationReplacement.create(to_replace: "1/2 ", replace_with: "0.5 ", execution_order: 10)
NotationReplacement.create(to_replace: "1/4 ", replace_with: "0.25 ", execution_order: 10)
NotationReplacement.create(to_replace: "x", replace_with: "-", execution_order: 10)
NotationReplacement.create(to_replace: "/", replace_with: "-", execution_order: 10)
NotationReplacement.create(to_replace: "-", replace_with: "|", execution_order: 999)

UnitAbbreviation.create(abbreviation: 'numbertencan', unit: '#10 can', execution_order: 102)
UnitAbbreviation.create(abbreviation: '#', unit: 'pound', execution_order: 102)
UnitAbbreviation.create(abbreviation: '#av', unit: 'pound', execution_order: 102)
UnitAbbreviation.create(abbreviation: '# av', unit: 'pound', execution_order: 102)
UnitAbbreviation.create(abbreviation: '#avg', unit: 'pound (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: '# avg', unit: 'pound (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'lbav', unit: 'pound (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'lb av', unit: 'pound (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'lbavg', unit: 'pound (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'lb avg', unit: 'pound (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'lb#', unit: 'pound', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'lbimport', unit: 'pound (import)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'lb import', unit: 'pound (import)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'kga', unit: 'kilogram (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'kgav', unit: 'kilogram (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'kg bag', unit: 'kilogram (bag)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'kgavg', unit: 'kilogram (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'kg av', unit: 'kilogram (average)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'kg up', unit: 'kilogram (minimum)', execution_order: 102)
UnitAbbreviation.create(abbreviation: '#up', unit: 'pound (minimum)', execution_order: 102)
UnitAbbreviation.create(abbreviation: '# up', unit: 'pound (minimum)', execution_order: 102)
UnitAbbreviation.create(abbreviation: 'pkg', unit: 'pack', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'rl', unit: 'roll', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'l', unit: 'liter', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'litre', unit: 'liter', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'liters', unit: 'liter', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'litres', unit: 'liter', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'lbs', unit: 'pound', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'sl', unit: 'slice', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'dzn', unit: 'dozen', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'z av', unit: 'ounce (average)', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'z avg', unit: 'ounce (average)', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'zav', unit: 'ounce (average)', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'zavg', unit: 'ounce (average)', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'oz av', unit: 'ounce (average)', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'ozav', unit: 'ounce (average)', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'ozavg', unit: 'ounce (average)', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'oz a', unit: 'ounce (average)', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'ltr', unit: 'liter', execution_order: 103)
UnitAbbreviation.create(abbreviation: 'grm', unit: 'gram', execution_order: 104)
UnitAbbreviation.create(abbreviation: 'ga', unit: 'gallon', execution_order: 105)
UnitAbbreviation.create(abbreviation: 'gal', unit: 'gallon', execution_order: 105)
UnitAbbreviation.create(abbreviation: 'env', unit: 'env', execution_order: 106)
UnitAbbreviation.create(abbreviation: 'ft', unit: 'foot', execution_order: 107)
UnitAbbreviation.create(abbreviation: 'ml bottles', unit: 'milliliter', execution_order: 107)
UnitAbbreviation.create(abbreviation: 'ml bottle', unit: 'milliliter', execution_order: 107)
UnitAbbreviation.create(abbreviation: 'env', unit: 'enveloped bag', execution_order: 107)
UnitAbbreviation.create(abbreviation: 'ge', unit: 'gram (average)', execution_order: 108)
UnitAbbreviation.create(abbreviation: 'sh', unit: 'sheet', execution_order: 109)
UnitAbbreviation.create(abbreviation: 'sht', unit: 'sheet', execution_order: 110)
UnitAbbreviation.create(abbreviation: 'doz', unit: 'dozen', execution_order: 110)
UnitAbbreviation.create(abbreviation: 'dz', unit: 'dozen', execution_order: 110)
UnitAbbreviation.create(abbreviation: 'oz', unit: 'ounce', execution_order: 111)
UnitAbbreviation.create(abbreviation: 'gm', unit: 'gram', execution_order: 112)
UnitAbbreviation.create(abbreviation: 'gr', unit: 'gram', execution_order: 113)
UnitAbbreviation.create(abbreviation: 'qt', unit: 'quart', execution_order: 114)
UnitAbbreviation.create(abbreviation: 'kg', unit: 'kilogram', execution_order: 115)
UnitAbbreviation.create(abbreviation: 'lb', unit: 'pound', execution_order: 116)
UnitAbbreviation.create(abbreviation: 'ml', unit: 'milliliter', execution_order: 117)
UnitAbbreviation.create(abbreviation: '"', unit: 'inch', execution_order: 118)
UnitAbbreviation.create(abbreviation: 'in', unit: 'inch', execution_order: 119)
UnitAbbreviation.create(abbreviation: 'ct', unit: 'count', execution_order: 120)
UnitAbbreviation.create(abbreviation: 'roll ', unit: 'roll', execution_order: 121)
UnitAbbreviation.create(abbreviation: 'pk', unit: 'pack', execution_order: 122)
UnitAbbreviation.create(abbreviation: 'cs', unit: 'case', execution_order: 123)
UnitAbbreviation.create(abbreviation: 'case', unit: 'case', execution_order: 123)
UnitAbbreviation.create(abbreviation: 'set', unit: 'set', execution_order: 124)
UnitAbbreviation.create(abbreviation: 'pak', unit: 'pack', execution_order: 125)
UnitAbbreviation.create(abbreviation: 'pt', unit: 'pint', execution_order: 126)
UnitAbbreviation.create(abbreviation: 'pnt', unit: 'pint', execution_order: 127)
UnitAbbreviation.create(abbreviation: 'tab', unit: 'tablet', execution_order: 128)
UnitAbbreviation.create(abbreviation: 'pair', unit: 'pair', execution_order: 129)
UnitAbbreviation.create(abbreviation: 'crate', unit: 'crate', execution_order: 130)
UnitAbbreviation.create(abbreviation: 'bu', unit: 'bunch', execution_order: 131)
UnitAbbreviation.create(abbreviation: 'bn', unit: 'bunch', execution_order: 132)
UnitAbbreviation.create(abbreviation: 'kilo', unit: 'kilogram', execution_order: 133)
UnitAbbreviation.create(abbreviation: 'quart', unit: 'quart', execution_order: 134)
UnitAbbreviation.create(abbreviation: 'por', unit: 'portion', execution_order: 135)
UnitAbbreviation.create(abbreviation: 'box', unit: 'box', execution_order: 136)
UnitAbbreviation.create(abbreviation: 'cup', unit: 'cup', execution_order: 137)
UnitAbbreviation.create(abbreviation: '''s', unit: 'count', execution_order: 138)
UnitAbbreviation.create(abbreviation: 'each', unit: 'each', execution_order: 139)
UnitAbbreviation.create(abbreviation: 'tray', unit: 'tray', execution_order: 140)
UnitAbbreviation.create(abbreviation: 'trays', unit: 'tray', execution_order: 141)
UnitAbbreviation.create(abbreviation: 'ea', unit: 'each', execution_order: 142)
UnitAbbreviation.create(abbreviation: 'pc', unit: 'piece', execution_order: 143)
UnitAbbreviation.create(abbreviation: 'lt', unit: 'liter', execution_order: 144)
UnitAbbreviation.create(abbreviation: 'bx', unit: 'box', execution_order: 145)
UnitAbbreviation.create(abbreviation: 'yd', unit: 'yard', execution_order: 146)
UnitAbbreviation.create(abbreviation: 'z', unit: 'ounce', execution_order: 147)
UnitAbbreviation.create(abbreviation: 'g', unit: 'gram', execution_order: 148)
UnitAbbreviation.create(abbreviation: 'k', unit: 'kilogram', execution_order: 149)
UnitAbbreviation.create(abbreviation: 'l', unit: 'liter', execution_order: 150)
UnitAbbreviation.create(abbreviation: 'm', unit: 'meter', execution_order: 151)
UnitAbbreviation.create(abbreviation: 'q', unit: 'quart', execution_order: 152)
UnitAbbreviation.create(abbreviation: 'c', unit: 'count', execution_order: 153)
UnitAbbreviation.create(abbreviation: 'e', unit: 'each', execution_order: 154)

